version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: eldora-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: eldora_db
    ports:
      - "5432:5432"
    volumes:
      - eldora_pgdata:/var/lib/postgresql/data

volumes:
  eldora_pgdata:
